version: '3.8'

services:
  apipagamentos:
    build:
      context: src/main/java/br/com/solidtechsolutions/apipagamentos/services/impls
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped