spring:
  application:
    name: apipagamentos
  datasource:
    url: jdbc:postgresql://172.233.26.93:5432/solidtechsolutions
    username: solidtechsolutions
    password: Reisapao123*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO

feign:
  client:
    config:
      default:
        loggerLevel: full

mercadopago:
  token: APP_USR-1440248300513896-050821-27314bb9bb417d3287c0d4a1f096bdf7-261919822

cors:
  config: "https://shop.karoleeduardo.com.br" # "*"
  #config: "*"
