spring:
  application:
    name: apipagamentos
  datasource:
    url: jdbc:postgresql://172.233.26.93:5432/solidtechsolutions
    username: solidtechsolutions
    password: Reisapao123*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO

feign:
  client:
    config:
      default:
        loggerLevel: full

mercadopago:
  token: APP_USR-3426870832768207-092909-a4262fd852c5ab88671cc8620e268435-213709863

cors:
  #config: "https://shop.karoleeduardo.com.br" # "*"
  config: "*"
